#!/bin/sh
# The Mac App Store screenshots, as recipes rather than as prose.
#
# `screenshot.sh` beside this is the driver and knows nothing about Filebase: it
# sizes the window, fronts it, drives the actions given, parks the pointer off
# the frame, captures, and refuses a result of the wrong size. `take-shots.sh`
# is the part between, and both of those are generated by `ship sync`. This file
# is the other half, the part that is Filebase's — which folder, which shot, and
# what has to happen in the window before the shutter.
#
# It is one file on purpose. Everything a person would change to retake a set
# lives at the top, and running it by hand is the same command CI runs:
#
#     ./packaging/demo-corpus.sh
#     ./packaging/macos/shots.sh --app dist/Filebase.app
#
# WHAT THE SET HAS TO SHOW, AND WHY
#
# Apple rejected segler's first four under guideline 2.3.3 — *the Mac
# screenshots do not show the actual app in use in the majority of the
# screenshots* — because nothing was selected in any of them, so its element
# pane read "select an element" in all four. A frame of an editor with nothing
# selected is a frame of a viewer.
#
# The same trap here wears different clothes: **a frame of Filebase with no
# query run is a frame of an empty window.** The first thing this application
# draws is a folder bar, an empty table and *Choose a folder, then run a query*.
# So every shot below has a query answered and a row selected, and two of them
# show something a viewer could not do — the notices under the count, and a
# container's whole description beside the table.
#
# THE COORDINATES
#
# Every one is measured from the frame's top-left corner at the size declared
# below. Change the size and they all move; that is why the size is a constant
# beside them rather than an argument with a default.
#
# **They are read off a reference frame, never guessed.** Dispatch
# `apple-silicon.yml` with `screenshots: reference`, which takes one plain frame
# and uploads it, and measure against that. odox learned this the expensive way
# and its `shots.ps1` still carries no actions for want of one.
#
# Author: David M. Anderson
# Built with AI assistance (Claude, Anthropic)

set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
root=$(CDPATH= cd -- "${here}/../.." && pwd)

# --- the configuration ------------------------------------------------------

# App Store Connect takes 1440x900 for macOS. Every coordinate below was read
# off a frame of this size.
WIDTH=1440
HEIGHT=900

# Filebase is handed what it opens as an argument and declares no document
# type, so the driver passes it rather than asking Launch Services to route it.
# This is what that flag is for, and it is why this file needs no staging step.
AS_ARGS=yes

# The folder to open. Built by `packaging/demo-corpus.sh`, which is committed so
# that the frames are of a corpus anyone can reproduce rather than of whatever
# happened to be on one machine, and which writes here by default. A fixed path
# rather than an argument, because `take-shots.sh` is generated and refuses an
# argument it does not know — the same way `DOCUMENT` is a fixed path in the
# applications that photograph a document.
CORPUS="${root}/dist/corpus"

# Where the shots land. Not committed: dist is where every built artefact goes.
OUTDIR="${root}/dist/screenshots"

# --- the shots --------------------------------------------------------------

# One shot to a line: name, then the actions that put the window into the state
# being photographed, in the order they are given.
#
#   --click X,Y    press a control
#   --double X,Y   press it twice inside the double-click interval
#   --type TEXT    type
#   --key NAME     one key, optionally with modifiers: cmd+a, return
#
# **The coordinates below are not filled in yet.** The reference frame has not
# been taken, and a coordinate guessed off a description of a window is a
# coordinate that photographs the wrong thing — which is worse than no set,
# because it passes. Dispatch `apple-silicon.yml` with `screenshots: reference`,
# measure, and replace the three `--click` pairs.
shots() {
    # The answer to a question, with a row selected: rows filling the table, a
    # column per metadata key, and the container on the right. This is the
    # frame that has to carry the listing, so it is first.
    #
    # Actions: tick recursive, type the query, run it, select a row.
    shot 01-a-folder-answering \
        --click RECURSIVE_XY \
        --click QUERY_BOX_XY --key cmd+a \
        --type 'select @path, title, status, governance.owner' --key return \
        --click FIRST_ROW_XY

    # A container in full: the payload card and the whole description as a
    # tree, beside the rows it came from. The empty `governance.owner` cell on
    # the row above is visible in the same frame, which is the ad-hoc-metadata
    # argument made in a picture rather than in a sentence.
    shot 02-a-container-in-full \
        --click RECURSIVE_XY \
        --click QUERY_BOX_XY --key cmd+a \
        --type 'select @path, title, status, governance.owner' --key return \
        --click FOURTH_ROW_XY

    # What the scan could not do, said out loud. The corpus has a container
    # whose `pages` is a word where the rest are numbers, and a file named like
    # a container that is not one, so this query produces both notices at once.
    shot 03-what-the-scan-noticed \
        --click RECURSIVE_XY \
        --click QUERY_BOX_XY --key cmd+a \
        --type 'select @path, title, pages where pages > 10' --key return \
        --click NOTICES_FOLD_XY
}

# --- the driving ------------------------------------------------------------

# Which folder this language opens.
#
# There is one set and it is English, because the listing is English: German is
# added to the application, to store-listing.toml and to this function in one
# pass. Refusing here rather than falling back is deliberate — the alternative
# is a German listing showing an English window, which is what happened to
# Slipcase Desktop's German customers.
for_language() {
    case "$1" in
        en|en-US|en-us) document=$CORPUS ;;
        de|de-DE|de-de)
            echo "shots.sh: no German set is written yet; the application has no German either" >&2
            exit 2 ;;
        *) echo "shots.sh: no set is written for $1" >&2; exit 2 ;;
    esac
}

. "${here}/take-shots.sh"
take_shots "$@"
